version: "3"

services:

  mongo:
    image: mongo:4
    ports:
      - 27017
    environment:
      - MONGODB_USER=""
      - MONGODB_PASS=""
    command:
      mongod

  installer:
    build: .
    image: evado-app-egov
    environment:
      - MONGO_HOST=mongo
      - WAIT_HOSTS=mongo:27017
    depends_on:
      - mongo
    command:
       node console/install

  server:
    image: evado-app-egov
    ports:
      - 3000:3000
    environment:
      - MONGO_HOST=mongo
    depends_on:
      - mongo
    command:
       node console/docker